---
- name: configure frontend service
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.command: dnf module install nginx:1.24 -y 

 
  - name: remove defalt content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip
   
  - name: unarchive frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: delete defalt nginx
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy nginx service
    ansible.builtin.template:
      src: nginx.service
      dest: /etc/nginx/nginx.conf
      remote_src: yes

      
  - name: start enable nginx
    ansible.builtin.service:
     name: nginx
     state: restarted
     enabled: yes 
