[mongodb]
mongodb-dev.solohunting.online

[catalogue]
catalogue-dev.solohunting.online

[redis]
redis-dev.solohunting.online

[user]
user-dev.solohunting.online

[cart]
cart-dev.solohunting.online

[mysql]
mysql-dev.solohunting.online

[shipping]
shipping-dev.solohunting.online

[rabbitmq]
rabbitmq-dev.solohunting.online

[payment]
payment-dev.solohunting.online


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.solohunting.online
REDIS_HOST=redis-dev.solohunting.online
USER_HOST=user-dev.solohunting.online
CART_HOST=cart-dev.solohunting.online
CATALOGUE_HOST=catalogue-dev.solohunting.online
MYSQL_HOST=mysql-dev.solohunting.online
SHIPPING_HOST=shipping-dev.solohunting.online

