---

- name: configure the redis server
  hosts: redis
  become: yes
  tasks:
  - name: enable redis 7
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: install redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: allow remoto connections, replace the file content
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

  - name: disable protectedmode no
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: protected-mode yes
      line: protected-mode no

  - name: restart the redis
    ansible.builtin.service:
      name: redis
      state: restart